name: pituitary
version: 0.0.1
synopsis: Reimplementation of R. Bertram works.
description: See README at <https://gitlab.unizar.es/bossa/Pituitary>
maintainer: Matias Bossa
license: MIT
category: Science
extra-source-files:
#  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - mwc-random
  - split
  - transformers
  - primitive
  - cassava
  - bytestring
  - vector
  - optparse-applicative
  - semigroups

library:
  source-dirs: src
  exposed-modules:
    - EuMa.Main

executable:
  main: Main.hs
  source-dirs: driver
  dependencies:
    - pituitary
